# Generated by Django 2.1.7 on 2019-05-02 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('fichero_consumo', models.FileField(upload_to='consumos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloPred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('fichero_modeloPred', models.FileField(blank=True, upload_to='modelos')),
                ('consumo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelosPred', to='forecasting.Consumo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
