# Generated by Django 2.1.7 on 2019-05-03 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255, unique=True)),
                ('fichero_prediccion', models.FileField(blank=True, upload_to='predicciones')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='modelopred',
            name='consumo_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.Consumo'),
        ),
        migrations.AlterField(
            model_name='modelopred',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelosPred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prediccion',
            name='modelopred_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.ModeloPred'),
        ),
    ]
