# Generated by Django 2.2.1 on 2019-06-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='prediccion_actualizada',
            field=models.BooleanField(default=False),
        ),
    ]
