# Generated by Django 2.2.1 on 2019-06-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifaelectrica',
            name='duracion_dos',
        ),
        migrations.RemoveField(
            model_name='tarifaelectrica',
            name='duracion_uno',
        ),
        migrations.RemoveField(
            model_name='tarifaelectrica',
            name='hora_ini_dos',
        ),
        migrations.RemoveField(
            model_name='tarifaelectrica',
            name='hora_ini_uno',
        ),
        migrations.RemoveField(
            model_name='tarifaelectrica',
            name='precio_dos',
        ),
        migrations.RemoveField(
            model_name='tarifaelectrica',
            name='precio_uno',
        ),
        migrations.AddField(
            model_name='tarifaelectrica',
            name='hora_fin_periodo_gracia',
            field=models.CharField(default='20:00', max_length=5),
        ),
        migrations.AddField(
            model_name='tarifaelectrica',
            name='hora_ini_periodo_gracia',
            field=models.CharField(default='14:00', max_length=5),
        ),
        migrations.AddField(
            model_name='tarifaelectrica',
            name='precio_periodo_general',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tarifaelectrica',
            name='precio_periodo_gracia',
            field=models.FloatField(default=0),
        ),
    ]
