# Generated by Django 2.2.1 on 2019-06-17 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costeinmueblete',
            old_name='tarifalectrica_asociada',
            new_name='tarifaelectrica_asociada',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='modelo_actualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TarifaMercadoRegulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('fichero_precios', models.FileField(upload_to='preciosMR')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifasmercadoregulado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
