# Generated by Django 2.2.1 on 2019-06-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_costeprediccionte'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoMercadoRegulado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_fichero', models.CharField(max_length=255)),
            ],
        ),
    ]
