# Generated by Django 2.2.1 on 2019-06-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_inmueble_prediccion_actualizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifamercadoregulado',
            name='fichero_precios_string',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
