# Generated by Django 2.2.1 on 2019-06-14 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_auto_20190613_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosteInmuebleTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('actualizado', models.BooleanField(default=True)),
                ('coste', models.FloatField()),
                ('inmueble_asociado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forecasting.Inmueble')),
                ('tarifalectrica_asociada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forecasting.TarifaElectrica')),
            ],
            options={
                'unique_together': {('inmueble_asociado', 'tarifalectrica_asociada')},
            },
        ),
    ]
