# Generated by Django 2.2.1 on 2019-05-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_auto_20190503_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='coste_tarifa_PPP',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
