# Generated by Django 2.2.1 on 2019-06-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0003_costeinmueblete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costeinmueblete',
            name='inmueble_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.Inmueble'),
        ),
        migrations.AlterField(
            model_name='costeinmueblete',
            name='tarifalectrica_asociada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.TarifaElectrica'),
        ),
    ]
