# Generated by Django 2.2.1 on 2019-05-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0003_consumo_coste_tarifa_ppp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='coste_tarifa_PPP',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
