# Generated by Django 2.2.1 on 2019-06-24 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0003_historicomercadoregulado'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_medio', models.FloatField()),
                ('consumo_max', models.FloatField()),
                ('consumo_max_fecha', models.CharField(max_length=255)),
                ('consumo_min', models.FloatField()),
                ('consumo_min_fecha', models.CharField(max_length=255)),
                ('mes_max_consumo', models.CharField(max_length=255)),
                ('inmueble_asociado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forecasting.Inmueble')),
            ],
        ),
    ]
