# Generated by Django 2.2.1 on 2019-06-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0004_auto_20190614_1830'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='costeinmueblete',
            unique_together=set(),
        ),
    ]
