# Generated by Django 2.2.1 on 2019-06-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0004_infoinmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='info_inmueble_actualizada',
            field=models.BooleanField(default=False),
        ),
    ]
