# Generated by Django 2.2.1 on 2019-05-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0004_auto_20190514_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='coste_tarifa_PPP',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
