# Generated by Django 2.2.1 on 2019-05-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0005_auto_20190514_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='coste_tarifa_EDP',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='consumo',
            name='coste_tarifa_VE',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
