# Generated by Django 2.2.1 on 2019-06-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0005_inmueble_info_inmueble_actualizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoinmueble',
            name='consumo_max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='infoinmueble',
            name='consumo_medio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='infoinmueble',
            name='consumo_min',
            field=models.FloatField(default=0),
        ),
    ]
