# Generated by Django 2.2.1 on 2019-06-24 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0006_auto_20190624_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoinmueble',
            name='inmueble_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.Inmueble'),
        ),
    ]
