# Generated by Django 2.2.1 on 2019-05-29 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecasting', '0007_auto_20190522_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('consumo_inmueble', models.FileField(upload_to='consumosInmuebles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', related_query_name='inmueble', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
