# Generated by Django 2.2.1 on 2019-06-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0009_prediccionconsumo_fichero_pconsumo_pprecio_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosteInmuebleML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='Tarifa ML', max_length=20)),
                ('empresa', models.CharField(blank=True, default='Empresa Privada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('coste', models.FloatField(blank=True, default=0)),
                ('inmueble_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.Inmueble')),
            ],
        ),
    ]
