# Generated by Django 2.2.1 on 2019-05-30 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecasting', '0009_auto_20190530_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoParcial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichero_consumo_parcial', models.FileField(upload_to='consumosParciales')),
                ('inmueble_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.Inmueble')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumosparciales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
