# Generated by Django 2.2.1 on 2019-07-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0010_costeinmuebleml'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEDP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='EDP', max_length=3)),
                ('ruta_modelo_edp', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('prediccion_edp_actualizada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloMR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='TTT', max_length=3)),
                ('ruta_modelo', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('prediccionTPF_actualizada', models.BooleanField(default=False)),
                ('prediccionEDP_actualizada', models.BooleanField(default=False)),
                ('prediccionVE_actualizada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloTPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='TPD', max_length=3)),
                ('ruta_modelo_tpd', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('prediccion_tpd_actualizada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloVE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='VE', max_length=3)),
                ('ruta_modelo_ve', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('prediccion_ve_actualizada', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='prediccionconsumo',
            name='modelo_edp_actulizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prediccionconsumo',
            name='modelo_tpd_actulizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prediccionconsumo',
            name='modelo_ve_actulizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prediccionconsumo',
            name='prediccion_edp_actualizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prediccionconsumo',
            name='prediccion_tpd_actualizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prediccionconsumo',
            name='prediccion_ve_actualizada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PrediccionVE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='VE', max_length=3)),
                ('coste_actualizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ruta_prediccion', models.CharField(max_length=255)),
                ('modelo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.ModeloVE')),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionTPD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='TPD', max_length=3)),
                ('coste_actualizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ruta_prediccion', models.CharField(max_length=255)),
                ('modelo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.ModeloTPD')),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionMR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='TTT', max_length=3)),
                ('costemr_actualizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ruta_prediccion', models.CharField(max_length=255)),
                ('modelo_mr_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.ModeloMR')),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionEDP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='EDP', max_length=3)),
                ('coste_actualizado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ruta_prediccion', models.CharField(max_length=255)),
                ('modelo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.ModeloEDP')),
            ],
        ),
        migrations.AddField(
            model_name='modelove',
            name='prediccionconsumo_asociada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.PrediccionConsumo'),
        ),
        migrations.AddField(
            model_name='modelotpd',
            name='prediccionconsumo_asociada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.PrediccionConsumo'),
        ),
        migrations.AddField(
            model_name='modelomr',
            name='prediccionconsumo_asociada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forecasting.PrediccionConsumo'),
        ),
        migrations.AddField(
            model_name='modeloedp',
            name='prediccionconsumo_asociada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.PrediccionConsumo'),
        ),
    ]
