# Generated by Django 2.2.1 on 2019-05-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0010_consumoparcial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='consumo_inmueble_parcial',
            field=models.FileField(blank=True, upload_to='consumosInmuebles'),
        ),
    ]
