# Generated by Django 2.2.1 on 2019-05-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0011_inmueble_consumo_inmueble_parcial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='consumo_inmueble_parcial',
            field=models.FileField(upload_to='consumosInmuebles'),
        ),
    ]
