# Generated by Django 2.2.1 on 2019-07-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0012_auto_20190711_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccionconsumo',
            name='coste_edp_actualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prediccionconsumo',
            name='coste_tpd_actualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prediccionconsumo',
            name='coste_ve_actualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CosteVEPrediccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='VE', max_length=3)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('coste', models.FloatField()),
                ('prediccion_consumo_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.PrediccionConsumo')),
                ('prediccion_mr_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.PrediccionTPD')),
            ],
        ),
        migrations.CreateModel(
            name='CosteTPDPrediccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='TPD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('coste', models.FloatField()),
                ('prediccion_consumo_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.PrediccionConsumo')),
                ('prediccion_mr_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.PrediccionTPD')),
            ],
        ),
        migrations.CreateModel(
            name='CosteEDPPrediccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='EDP', max_length=3)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('coste', models.FloatField()),
                ('prediccion_consumo_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.PrediccionConsumo')),
                ('prediccion_mr_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.PrediccionTPD')),
            ],
        ),
    ]
