# Generated by Django 2.2.1 on 2019-05-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0012_auto_20190530_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='consumo_inmueble_parcial',
            field=models.FileField(blank=True, upload_to='consumosInmuebles'),
        ),
    ]
