# Generated by Django 2.2.1 on 2019-07-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0013_auto_20190712_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='costeedpprediccion',
            name='ruta_predicciones',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='costetpdprediccion',
            name='ruta_predicciones',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='costeveprediccion',
            name='ruta_predicciones',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
