# Generated by Django 2.2.1 on 2019-06-01 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecasting', '0014_auto_20190531_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloConsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('fichero_modelo_inmueble', models.FileField(blank=True, upload_to='modelos')),
                ('inmueble_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.Inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='PrediccionConsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('fichero_prediccion_consumo', models.FileField(blank=True, upload_to='predicciones')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modelo_consumo_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.ModeloConsumo')),
            ],
        ),
    ]
