# Generated by Django 2.2.1 on 2019-07-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0014_auto_20190712_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costeedpprediccion',
            name='prediccion_mr_asociada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.PrediccionEDP'),
        ),
        migrations.AlterField(
            model_name='costeveprediccion',
            name='prediccion_mr_asociada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.PrediccionVE'),
        ),
    ]
