# Generated by Django 2.2.1 on 2019-06-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0015_modeloconsumo_prediccionconsumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediccionconsumo',
            name='created_by',
        ),
    ]
