# Generated by Django 2.2.1 on 2019-07-15 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0016_auto_20190713_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccionconsumo',
            name='costes_ml_actualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='coste_edp_actualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='coste_tpd_actualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='coste_ve_actualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CostePrediccionML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='Tarifa ML', max_length=20)),
                ('empresa', models.CharField(blank=True, default='Empresa Privada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('coste', models.FloatField(blank=True, default=0)),
                ('prediccion_consumo_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecasting.PrediccionConsumo')),
            ],
        ),
    ]
