# Generated by Django 2.2.1 on 2019-06-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0016_remove_prediccionconsumo_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='consumo_inmueble',
            field=models.BinaryField(),
        ),
    ]
