# Generated by Django 2.2.1 on 2019-06-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0017_auto_20190608_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='consumo_inmueble',
            field=models.FileField(upload_to='consumosInmuebles'),
        ),
    ]
