# Generated by Django 2.2.1 on 2019-07-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0017_auto_20190715_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccionconsumo',
            name='costes_personalizadas_actualizado',
            field=models.BooleanField(default=False),
        ),
    ]
